spring:
  mail:
    host: smtp.gmail.com
    username: jasser.hedhli@etudiant-isi.utm.tn
    password: edsraiejeuqdqdmd
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true